baseURL = "https://github.wdf.sap.corp/pages/I820920/capextensibility"
languageCode = "en-us"
title = "SAP Cloud For Utilities"
publishDir = "docs"
theme = "geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  # (Optional, default false) Render menu from data file im 'data/menu/main.yaml'.
  geekdocMenuBundle = true
  

  geekdocLogo = "sap-logo-svg.svg"
